### ISSUE TITLE
The IAS shall show a top-level status of all monitored systems summarizing their health state

### ISSUE THREAD

**Issue by acaproni** [IntegratedAlarmSystem-Group/ias-display#16] opened 2018-03-16 12:35 UTC
This is REQ-FUNC-002 requirements:
This includes all systems that will be monitored (power plant, weather stations, ALMA antenna array, etc.). The top-level status of each system shall summarize the status of all elements that belong in the monitored system

**Comment by acaproni** [comment] 2018-03-16 12:53
From REQ-PRES-001:
_The alarm system must always have a main alarm display visible when running. It must be able to display all the alarms that are present in the configured system. Most of these alarms will be shown in summary elements, but it is important that any alarm condition will be visible from the main overview panel, e.g. through a blinking and appropriately colour coded element_

**Comment by sfehlandt** [comment] 2018-03-26 13:59
This is a duplicate of #12. However, this description is better so I will close the other one.

**Comment by sfehlandt** [comment] 2018-06-01 02:46
Closed by: 9bbe8bc74dbf84628ca63640d8ce37b4ebba3dec

**Closed by sfehlandt** 2018-06-01 02:46 UTC
